name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      env_path:
        description: 'Path to the environment directory'
        required: true
        type: string

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: write    # This is required for actions/checkout

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: github-actions-ci
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.6.0

      - name: Terraform Destroy
        run: |
          cd ${{ github.event.inputs.env_path }}
          terraform init
          terraform destroy -auto-approve \
            -var-file="common.account.auto.tfvars" \
            -var-file="common.region.auto.tfvars"
